### ISSUE TITLE
'Last updated' field on status.nixos.org does not reflect expected value.

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixos-status#7]
The values in the column ''Last updated' on https://status.nixos.org are [computed](https://github.com/NixOS/nixos-org-configurations/blob/3294705/delft/eris/status-page/status.js) based on the timestamp in the head commit of the channel. But due to merging it often happens that the timestamp of the head commit is much older than its parent commits, leading confused people to create [issues in nixpkgs](https://github.com/NixOS/nixpkgs/issues/89460). See the [commits pushed on June 8, 2020](https://github.com/NixOS/nixpkgs-channels/commits/nixos-20.03/) for an example.
In the JSON info gathered through GitHubs API using `comitter.date` instead of `commit.date` would give the timestamp of the actual channel push. This would give a proper age indication on `status.nixos.org`.

**Comment by garbas** [comment]
@wamserma  is this still the issue? As far as I can see the date is now recorded in Prometheus and that is what status.nixos.org is querying.

I'm closing the issue but please reopen it if I made wrong judgement.

**Comment by wamserma** [comment]
I think this is fine now.

**Comment by vcunat** [comment]
It seems that the currently shown stamp is the moment the channel got **published**.  From my point of view, I prefer the moment when its commit was **pushed** (to github.com/nixos/nixpkgs).

I can recall cases when they were very far, typically when a channel is blocked.  It's when I retrospectively restarted some older transient failures to advance the channel at least a little, even if the corresponding commit is a few days old already &ndash; and then status.nixos.org shows the channel as fresh even if it isn't.

Maybe my expectations aren't in majority?  Anyway, I keep using my script above...

**Comment by garbas** [comment]
@vcunat I see no reason why not to have a new column "Last pushed". Feel free to send PR and I'll review it.
