### ISSUE TITLE
The website doesn't load information from Prometheus ?

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixos-status#9]
It's stuck for me with:

![ZENIX-selection-2021-03-19T09:52:28+02:00](https://user-images.githubusercontent.com/10998835/111748157-1689ee00-8888-11eb-8243-b5f13cc5db5b.png)

**Comment by jshholland** [comment]
Seems like the SSL certificate for monitoring.nixos.org has expired.

**Comment by grahamc** [comment]
Seems solved :).
